title: Howard Chu's Homepage
email: howardchu95@gmail.com
description: Howard Chu's Homepage
  
baseurl: ""
url: ""
twitter_username: howardchu_
github_username:  Sberm

theme: jekyll-whiteglass
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

# index page
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 20

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
